### ISSUE TITLE
It uses php

### ISSUE THREAD

**Issue by Aurora0000** [Tel-Aviv/TTK-CMS#1]

**Comment by Tel-Aviv** [comment]
ahha

**Comment by Aurora0000** [comment]
Do not laugh at my issues. FIX IT

**Comment by Tel-Aviv** [comment]
So what do you want it in then?

**Comment by Aurora0000** [comment]
It shall be in Node.js

**Comment by Tel-Aviv** [comment]
Eww

**Comment by chronium** [comment]
Python! Python is the best thing in the world!!! Sliced bread is not as cool as Django, not even close.

**Comment by Aurora0000** [comment]
NO
